#!/usr/bin/env python3
"""
data_quality.py — Phase 8 Feature 4: Nutrition Data Quality Scoring.

Each food record carries a quality label so downstream consumers know
how much to trust the numbers (especially important when mixing TW_FDA,
USDA, and AI estimates).
"""

from __future__ import annotations

from dataclasses import dataclass, asdict
from typing import Literal, Optional


SourceType = Literal["TW_FDA", "USDA", "GI_LLM", "AI_EST", "USER_INPUT", "UNKNOWN"]
MatchMethod = Literal["exact", "alias", "fuzzy", "llm_estimate", "manual", "unknown", "auto"]


@dataclass
class NutritionQuality:
    source_confidence: float
    nutrition_confidence: float
    match_method: MatchMethod
    quality_label: str
    quality_notes: str

    def to_dict(self) -> dict:
        return asdict(self)


def _infer_match_method(score: float) -> MatchMethod:
    if score >= 0.95:
        return "exact"
    if score >= 0.80:
        return "alias"
    if score >= 0.50:
        return "fuzzy"
    return "unknown"


def estimate_nutrition_quality(
    *,
    source: Optional[str] = None,
    match_score: Optional[float] = None,
    match_method: MatchMethod = "unknown",
    has_required_macros: bool = True,
    is_ai_estimate: bool = False,
) -> NutritionQuality:
    """Estimate data quality for a nutrition record.

    Args:
        source:        Data source (TW_FDA / USDA / AI_EST / USER_INPUT / ...).
        match_score:   Search match confidence 0–1 (used when match_method=auto).
        match_method:  How the food was matched (exact/alias/fuzzy/llm_estimate/manual/unknown).
        has_required_macros: True when cal/protein/carb/fat are all present.
        is_ai_estimate: True when values were generated by an LLM / heuristic.

    Returns:
        NutritionQuality dataclass.
    """
    source_upper = (source or "UNKNOWN").upper()

    # ── Base source confidence ────────────────────────────────────────────
    if source_upper == "TW_FDA":
        source_conf = 0.95
    elif source_upper == "USDA":
        source_conf = 0.90
    elif source_upper == "GI_LLM":
        source_conf = 0.55
    elif source_upper == "AI_EST" or is_ai_estimate:
        source_conf = 0.35
    elif source_upper == "USER_INPUT":
        source_conf = 0.65
    else:
        source_conf = 0.50

    # ── Auto-resolve match_method from match_score if requested ────────
    if match_method == "auto":
        if match_score is None:
            match_method = "unknown"
        elif match_score >= 0.95:
            match_method = "exact"
        elif match_score >= 0.80:
            match_method = "alias"
        elif match_score >= 0.50:
            match_method = "fuzzy"
        else:
            match_method = "unknown"

    # ── Adjustments ────────────────────────────────────────────────────────
    method_adj = {
        "exact": 0.0,
        "alias": -0.05,
        "fuzzy": -0.15,
        "llm_estimate": -0.35,
        "manual": -0.10,
        "unknown": -0.20,
    }.get(match_method, -0.20)

    score_adj = 0.0
    if match_score is not None:
        if match_score >= 0.90:
            score_adj = 0.0
        elif match_score >= 0.70:
            score_adj = -0.08
        elif match_score >= 0.50:
            score_adj = -0.18
        else:
            score_adj = -0.30

    macro_adj = 0.0 if has_required_macros else -0.25

    nutrition_conf = max(0.05, min(1.0, source_conf + method_adj + score_adj + macro_adj))

    # ── Quality label ────────────────────────────────────────────────────────
    if nutrition_conf >= 0.85:
        label = "high"
    elif nutrition_conf >= 0.65:
        label = "medium"
    elif nutrition_conf >= 0.45:
        label = "low"
    else:
        label = "very_low"

    # ── Quality notes ───────────────────────────────────────────────────────
    notes: list[str] = []
    if is_ai_estimate or source_upper == "AI_EST":
        notes.append("AI 估算值，誤差可能較高")
    if match_method == "fuzzy":
        notes.append("模糊匹配，可能不是完全相同食物")
    if match_method == "llm_estimate":
        notes.append("AI 估算的營養值，僅供參考")
    if not has_required_macros:
        notes.append("缺少部分巨量營養素資料")

    return NutritionQuality(
        source_confidence=round(source_conf, 3),
        nutrition_confidence=round(nutrition_conf, 3),
        match_method=match_method,
        quality_label=label,
        quality_notes="；".join(notes) if notes else "資料品質正常",
    )


def quick_quality_label_from_source(
    source: str,
    confidence: float = 1.0,
) -> str:
    """Fast quality label for food_logs when full NutritionQuality is not needed.

    Used by calorie_tracker.log_meal_analysis() / log_meal_manual() to stamp
    each written row with a quality label without importing data_quality in
    hot paths.

    Returns one of: high | medium | low | very_low
    """
    src = source.upper() if source else "UNKNOWN"
    if src == "TW_FDA":
        conf = 0.95
    elif src == "USDA":
        conf = 0.90
    elif src == "GI_LLM":
        conf = 0.55
    elif src == "AI_EST":
        conf = 0.35
    elif src == "USER_INPUT":
        conf = 0.65
    else:
        conf = 0.50

    # Blend with per-row confidence when available
    effective = conf * 0.6 + (confidence or 0) * 0.4

    if effective >= 0.85:
        return "high"
    if effective >= 0.65:
        return "medium"
    if effective >= 0.45:
        return "low"
    return "very_low"